### PR TITLE
Don't import `where()` from ape

### PR DESCRIPTION
**Pull request by DavisVaughan**
The next version of dplyr will export `where()` and this causes a name conflict with `ape::where()` because you import all of dplyr and all of ape. This PR fixes this by adding an exception for `ape::where()`. You seem to actually use `where()` in a dplyr context, so this made more sense to me.

We are releasing dplyr to CRAN today. Unfortunately we missed your package in our round of revdep PRs a month ago because autoGO was just released to CRAN in January.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by fabio-t** [comment]
Thank you @DavisVaughan, please make a PR on the develop branch here https://github.com/mpallocc/auto-go and we'll integrate it in our next release :)

**Comment by DavisVaughan** [comment]
@fabio-t it is helpful for us if you include a BugReports URL like this https://github.com/r-lib/vctrs/blob/af3fcc486664e30b588df1296a212e583ef00d18/DESCRIPTION#L28

We can automatically detect that and that lets us send the PR to the right place.

**Comment by fabio-t** [comment]
Will do!

**Comment by fabio-t** [comment]
@gaborcsardi the issues has been fixed and I've added the BugReports for the next release, you can close here if you wish :pray:

**Pull request closed without merging**
